### ISSUE TITLE
Improve description of relationship between Debugger window and Steam Overlay

### ISSUE THREAD

**Issue by darienm** [Whitebrim/Payday3-ShowCode#1]
This mod works awesomely. Nice job. The description that mentions the console and Steam overlay, though, is a bit vague for non-programmers and could probably be refined and additional tips added. An example for your consideration:

Old: The keypad code will be logged to the console, which you need to see. The downside is that it launches before the game, and the Steam overlay will operate in the console instead of in the game.

New: This mod launches the Unreal Engine Debugging Tool before PayDay 3 completely starts up. This causes the Steam Overlay to display in this app, and not inside of PayDay 3. A simple Alt-Tab gets you to the Debugging Tool and back. It's probably also useful to type the word 'code' into the filter field once it's fully loaded so that all the other debugging info doesn't crowd the window or cause the game codes to scroll away too quickly.

**Comment by Whitebrim** [comment]
Thanks, changed.
